### ISSUE TITLE
Link to docs is broken

### ISSUE THREAD

**Issue by StephenHnilica** [runpod-workers/worker-whisper#2]
[docs.runpod.io/reference/whisper](https://docs.runpod.io/reference/whisper) redirects to https://www.doc.runpod.io/reference/faster-whisper, which is broken.

Need to update the URL to https://doc.runpod.io/reference/whisper (or https://doc.runpod.io/reference/faster-whisper, which is where the previous URL redirects to)

**Comment by AllysonRosenthal** [comment]
Thanks for the catch! Fixed with https://github.com/runpod/docs/pull/25. @justinmerrell can you close this?
