### ISSUE TITLE
Add support for large-v3

### ISSUE THREAD

**Issue by dudztroyer** [runpod-workers/worker-whisper#3]
Whisper has a large-v3 model that isn't available here on a runpod worker. Is it possible to add it?

If I'm not wrong, just need to add the model version to the download weights and it should work.

Here are the paths needed for the update: 

```
_MODELS = {
...
    "large-v3": "https://openaipublic.azureedge.net/main/whisper/models/e5b1a55b89c1367dacf97e3e19bfd829a01529dbfdeefa8caeb59b3f1b81dadb/large-v3.pt",
...
}

_ALIGNMENT_HEADS = {
...
    "large-v3": b"ABzY8gWO1E0{>%R7(9S+Kn!D~%ngiGaR?*L!iJG9p-nab0JQ=-{D1-g00",
...
}
```

Source: https://github.com/openai/whisper/blob/main/whisper/__init__.py

**Comment by solanovisitor** [comment]
Any updates on this?

**Comment by dudztroyer** [comment]
BUMP

**Comment by pandyamarut** [comment]
@dudztroyer Added the V3. Is there anything else?

**Comment by pandyamarut** [comment]
Closing this issue. If we need anything else to update. Please create an another issue. Thanks
